apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeweb
spec:
  selector:
    matchLabels:
      app: nodeweb
  template:
    metadata:
      labels:
        app: nodeweb
    spec:
      containers:
      - name: nodeweb
        image: theoafactor/nodeweb:stable1
        resources:
          limits:
            memory: "108Mi"
            cpu: "50m"
        ports:
        - containerPort: 4343
